{% set python_min = "3.12" %}
{% set name = "pidgen2" %}
{% set version = "0.3.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: 82a1b7f6e1aaf5126175fe2ab3e44f4ec10e261024592c3bb0f4a638b9467228

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.14
    - pandas >=2.2
    - matplotlib-base >=3.9
    - uproot ==5.4.2
    - xrootd >=5.7
    - fsspec-xrootd >=0.4

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apoluekt
    - chrisburr
