{% set name = "pidgen2" %}
{% set version = "0.3.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: b58c4bb91b6bf84174e947fa82b3b6a2dd05d04dccbd001535b3518529d89719

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.12
    - numpy ==2.0.2
    - scipy ==1.14.1
    - pandas ==2.2.3
    - matplotlib ==3.9.2
    - uproot ==5.4.2
    - xrootd ==5.7.1
    - fsspec-xrootd ==0.4.0
    - root ==6.32.02

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apoluekt
    - chrisburr
