{% set name = "pidgen2" %}
{% set version = "0.3.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: f4ae13c5cef6751ee9c41ccfae5d432a6ec65172fdf55b85d6e69cd0f8b7d61e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy <2
    - scipy
    - pandas
    - matplotlib-base
    - uproot <5.2
    - xrootd ==5.2

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apoluekt
    - chrisburr
